"""align models with api response

Revision ID: 6337929afd58
Revises: b7e2f1a3c4d5
Create Date: 2026-03-11 00:22:08.421356

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '6337929afd58'
down_revision: Union[str, Sequence[str], None] = 'b7e2f1a3c4d5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_preferences')
    op.add_column('activities', sa.Column('estimated_cost_usd', sa.String(length=20), nullable=True))
    op.drop_column('activities', 'weather_note')
    op.drop_column('activities', 'sort_order')
    op.drop_column('activities', 'latitude')
    op.drop_column('activities', 'estimate_cost')
    op.drop_column('activities', 'longitude')
    op.add_column('itinerary_dates', sa.Column('theme', sa.String(length=255), nullable=True))
    op.drop_column('itinerary_dates', 'date')
    op.add_column('trips', sa.Column('origin', sa.String(length=255), nullable=True))
    op.add_column('trips', sa.Column('month', sa.String(length=20), nullable=True))
    op.add_column('trips', sa.Column('duration_days', sa.Integer(), nullable=False))
    op.add_column('trips', sa.Column('budget', sa.String(length=20), nullable=True))
    op.add_column('trips', sa.Column('trip_vibe', sa.Text(), nullable=True))
    op.drop_column('trips', 'purpose')
    op.drop_column('trips', 'constraints')
    op.drop_column('trips', 'trip_number')
    op.drop_column('trips', 'traveler_count')
    op.drop_column('trips', 'end_date')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('trips', sa.Column('end_date', sa.DATE(), autoincrement=False, nullable=False))
    op.add_column('trips', sa.Column('traveler_count', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('trips', sa.Column('trip_number', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('trips', sa.Column('constraints', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('trips', sa.Column('purpose', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('trips', 'trip_vibe')
    op.drop_column('trips', 'budget')
    op.drop_column('trips', 'duration_days')
    op.drop_column('trips', 'month')
    op.drop_column('trips', 'origin')
    op.add_column('itinerary_dates', sa.Column('date', sa.DATE(), autoincrement=False, nullable=False))
    op.drop_column('itinerary_dates', 'theme')
    op.add_column('activities', sa.Column('longitude', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('estimate_cost', postgresql.ENUM('free', 'low', 'mid', 'high', name='costband'), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('latitude', sa.VARCHAR(length=20), autoincrement=False, nullable=True))
    op.add_column('activities', sa.Column('sort_order', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('activities', sa.Column('weather_note', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_column('activities', 'estimated_cost_usd')
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('origin_city', sa.VARCHAR(length=255), autoincrement=False, nullable=True),
    sa.Column('budget_tier', postgresql.ENUM('budget', 'mid_range', 'luxury', name='budgettier'), autoincrement=False, nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.TEXT()), autoincrement=False, nullable=True),
    sa.Column('pace', postgresql.ENUM('slow', 'moderate', 'fast_paced', name='pacepreference'), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('user_preferences_user_id_fkey')),
    sa.PrimaryKeyConstraint('id', name=op.f('user_preferences_pkey')),
    sa.UniqueConstraint('user_id', name=op.f('user_preferences_user_id_key'), postgresql_include=[], postgresql_nulls_not_distinct=False)
    )
    # ### end Alembic commands ###
