"""initial_schema

Revision ID: ca014a679ecd
Revises: 
Create Date: 2026-03-01 00:53:39.632973

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ca014a679ecd'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('users',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('trips',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('destination', sa.String(length=255), nullable=False),
    sa.Column('start_date', sa.Date(), nullable=False),
    sa.Column('end_date', sa.Date(), nullable=False),
    sa.Column('purpose', sa.Text(), nullable=True),
    sa.Column('traveler_count', sa.Integer(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.Column('share_token', sa.String(length=12), nullable=True),
    sa.Column('trip_number', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('generating', 'ready', 'error', name='tripstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('share_token')
    )
    op.create_table('user_preferences',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('origin_city', sa.String(length=255), nullable=True),
    sa.Column('budget_tier', sa.Enum('budget', 'mid_range', 'luxury', name='budgettier'), nullable=True),
    sa.Column('interests', postgresql.ARRAY(sa.Text()), nullable=True),
    sa.Column('pace', sa.Enum('slow', 'moderate', 'fast_paced', name='pacepreference'), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    op.create_table('itinerary_dates',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('trip_id', sa.UUID(), nullable=False),
    sa.Column('day_number', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.ForeignKeyConstraint(['trip_id'], ['trips.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('activities',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('itinerary_date_id', sa.UUID(), nullable=False),
    sa.Column('place_name', sa.String(length=255), nullable=False),
    sa.Column('place_id', sa.String(length=100), nullable=True),
    sa.Column('category_tag', sa.Enum('food', 'nature', 'culture', 'nightlife', 'adventure', 'wellness', name='categorytag'), nullable=True),
    sa.Column('time_window', sa.String(length=20), nullable=True),
    sa.Column('estimate_cost', sa.Enum('free', 'low', 'mid', 'high', name='costband'), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('weather_note', sa.Text(), nullable=True),
    sa.Column('latitude', sa.String(length=20), nullable=True),
    sa.Column('longitude', sa.String(length=20), nullable=True),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['itinerary_date_id'], ['itinerary_dates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('activities')
    op.drop_table('itinerary_dates')
    op.drop_table('user_preferences')
    op.drop_table('trips')
    op.drop_table('users')
    # ### end Alembic commands ###
